### ISSUE TITLE
pygstc.gstcerror.GstdError: ('State error', 14)

### ISSUE THREAD

**Issue by 07hokage** [RidgeRun/gtc-2020-demo#4]
I'm trying to run the script with an usb cam and csi camera. 
I'm getting the following error

`Creating pipeline: camera0`
`Creating pipeline: camera0_rgba_nvmm`
`Creating pipeline: camera1`
`Creating pipeline: camera1_rgba_nvmm`
`Creating pipeline: deepstream`
`Creating pipeline: h264`
`Creating pipeline: h265`
`Creating pipeline: vp9`
`Creating pipeline: jpeg`
`Creating pipeline: record_h264`
`Creating pipeline: record_h265`
`Creating pipeline: record_vp9`
`Creating pipeline: snapshot`
`Creating pipeline: display`
`Playing pipeline: camera0`
`Playing pipeline: camera0_rgba_nvmm`
`Playing pipeline: camera1`
`Playing pipeline: camera1_rgba_nvmm`
`Playing pipeline: deepstream`
`Traceback (most recent call last):`
  `File "media-server.py", line 92, in <module>`
    `pipeline.play()`
  `File "media-server.py", line 16, in play`
    `self._client.pipeline_play(self._name)`
  `File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 894, in pipeline_play`
    `self._send_cmd_line(['pipeline_play'] + parameters)`
  `File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 232, in _send_cmd_line`
    `result['code'])`
`pygstc.gstcerror.GstdError: ('State error', 14)`

I traced back the  line 232 in `/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py` and also checked that parameters for deepstream were being returned as `parameters['deepstream']` after that _send_cmd_line is getting failed.  Any way to figure out what's the issue?

Platform: Jetson Nano
Deepstream version: 5.0

**Comment by michaelgruner** [comment]
Hi, one of the developers of the demo will respond with something more akin to the specific pipeline.

As a Gstd developer I may help you interpret the backtrace. In these lines:

> Playing pipeline: deepstream
> Traceback (most recent call last):
> File "media-server.py", line 92, in <module>
> pipeline.play()
> File "media-server.py", line 16, in play
> self._client.pipeline_play(self._name)
> File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 894, in pipeline_play
> self._send_cmd_line(['pipeline_play'] + parameters)
> File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 232, in _send_cmd_line
> result['code'])
> pygstc.gstcerror.GstdError: ('State error', 14)
> 
pygstc is telling you that Gstd (the server) failed with a State Error. The basically means the it was unable to set the pipeline to playing, for whatever reason (typically caps negotiation).

I would recommend running Gstd with debug enabled. Note that it is Gstd and not the script, what needs to be configured with debug. 

```
GST_DEBUG=*:2 gstd
```

Michael

**Comment by 07hokage** [comment]
Hi @michaelgruner  I initialised gstd with the following command: `gstd -p 5000 GST_DEBUG="*:2"`
After running the media-server.py file, i got the same error.

Here is the gstd log file updated after the operation.
[gstd.log](https://github.com/RidgeRun/gtc-2020-demo/files/5506050/gstd.log)

and the contents of gst.log file:
`0:00:06.319414268 [334m 9243[00m   0x7f9c636ad0 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:766:gst_nvinfer_start:<nvinfer0>[00m error: Configuration file parsing failed
0:00:06.321541039 [334m 9243[00m   0x7f9c636ad0 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:766:gst_nvinfer_start:<nvinfer0>[00m error: Config file path: ../deepstream-models/config_infer_primary_4_cameras.txt`

Is seems to fail as it cannot parse the config file. Is the deepstream 5.0 version causing this  error?

**Comment by michaelgruner** [comment]
Ah yes, that seems like it. Please recall that the path should be relative to Gstd and not the script (since it’s the process containing the pipelines). Did you try absolute paths?

**Comment by 07hokage** [comment]
@michaelgruner  Thank you very much.  I changed all the locations to absolute paths. It's working now. I now get it.  Things should be seen with respect to Gstd and not the script.  
Just a small information required before closing this issue. The display stream from `nvarguscamerasrc` seems to be delayed by 2-3 seconds. I'm using `IMX219` CSI camera.  Any reason why it could be happening ?

**Comment by michaelgruner** [comment]
You need to keep an eye on the different potential buffering points in the pipe. These are typically the queues and the interpipesrc.

I would start with the camera. The nvargusvamera has an internal queue which may grow very large. You may want to place a “queue max-size-buffers=3 leaky=downstream” right after the camera. This will avoid the camera from accumulating. 

Then I would try setting the “block” property of the interpipesrc to TRUE. This will impede the element to accumulate buffers. If that doesn’t help, I recommend you try limiting the max-size-XXX properties of the queues, until you find where is the bottleneck. 

Finally, you may want to give the latency tracer a go, to see if any other element may be causing the delay. Encoders are candidates to cause this.

**Comment by 07hokage** [comment]
Thanks @michaelgruner for the support.  Setting max-size-buffers=1 reduced the latency by a lot.  Closing the issue now

**Comment by Tathagatd96** [comment]
@SaiHaneeshAllu can you clarify which config files you have modified and which paths inside it do I have to change with the absolute paths.

**Comment by Tathagatd96** [comment]
@SaiHaneeshAllu can you specify which config files you modified and which paths have to be changed?

**Comment by 07hokage** [comment]
@Tathagatd96  In the media-server.py file, Line 56 has Deepstream pipeline initialised. In that initialisation line, configuration files are specified. Just change the paths to absolute paths

**Comment by Tathagatd96** [comment]
@SaiHaneeshAllu Thanks for the clarification. I had one more question. Is it possible to run this demo with offline saved videos?

**Comment by 07hokage** [comment]
Yes you can run. But then you need to initialize deep-stream pipeline with the files instead of cameras.  You may check [this](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps) out. Try out the examples.

**Comment by Tathagatd96** [comment]
@SaiHaneeshAllu Ok Ill work out the examples and hopefully it works. Thanks again.
