### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by neilyoung** [RidgeRun/gtc-2020-demo#8]
Hi,

thanks for sharing this wonderful work (including your extra plugins). I was able to follow it on a Jetson Nano, three cameras attached. I did change the video sources according to my setup, commented all converters (expect JPG) and let it run.

After a while the directory contained some .mkv files and two snapshots, all empty.

During the run I could not see any problems: All pipelines have been build up correctly and could be started. But I was expecting a display, containing the inference results.

Since I'm also having this "no display" problem with the official Nvidia deepstream pyhton example, I'm now wondering, how I could approach this problem.

Finally: I think, it is a bit out of your focus, but am I right, if I suppose, that I'm NOT able to intercept the inference results on this way?

But this later. For now I would either like to see a snapshot or my display :)

**Comment by neilyoung** [comment]
So basically this is what I have made from your code:

```python

import time
from pygstc.gstc import *

# Create PipelineEntity object to manage each pipeline
class PipelineEntity(object):
    def __init__(self, client, name, description):
        self._name = name
        self._description = description
        self._client = client
        print("Creating pipeline: " + self._name)
        self._client.pipeline_create(self._name, self._description)
    def play(self):
        print("Playing pipeline: " + self._name)
        self._client.pipeline_play(self._name)
    def stop(self):
        print("Stopping pipeline: " + self._name)
        self._client.pipeline_stop(self._name)
    def delete(self):
        print("Deleting pipeline: " + self._name)
        self._client.pipeline_delete(self._name)
    def eos(self):
        print("Sending EOS to pipeline: " + self._name)
        self._client.event_eos(self._name)
    def set_file_location(self, location):
        print("Setting " + self._name + " pipeline recording/snapshot location to " + location);
        filesink_name = "filesink_" + self._name;
        self._client.element_set(self._name, filesink_name, 'location', location);
    def listen_to(self, sink):
        print(self._name + " pipeline listening to " + sink);
        self._client.element_set(self._name, self._name + '_src', 'listen-to', sink);

pipelines_base = []

# Create GstD Python client
client = GstdClient()

# Create camera pipelines
camera0 = PipelineEntity(client, 'camera0', 'v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480 ! interpipesink name=camera0 forward-events=true forward-eos=true sync=false')
pipelines_base.append(camera0)

camera0_rgba_nvmm = PipelineEntity(client, 'camera0_rgba_nvmm', 'interpipesrc listen-to=camera0 ! video/x-raw,format=YUY2,width=640,height=480 ! videoconvert ! video/x-raw,format=NV12,width=640,height=480 ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=640,height=480 ! queue ! interpipesink name=camera0_rgba_nvmm forward-events=true forward-eos=true sync=false caps=video/x-raw(memory:NVMM),format=RGBA,width=640,height=480,pixel-aspect-ratio=1/1,interlace-mode=progressive,framerate=30/1')
pipelines_base.append(camera0_rgba_nvmm)

camera1 = PipelineEntity(client, 'camera1', 'v4l2src device=/dev/video2 ! video/x-raw,format=YUY2,width=640,height=480 ! interpipesink name=camera1 forward-events=true forward-eos=true sync=false')
pipelines_base.append(camera1)

camera1_rgba_nvmm = PipelineEntity(client, 'camera1_rgba_nvmm', 'interpipesrc listen-to=camera1 ! video/x-raw,format=YUY2,width=640,height=480 ! videoconvert ! video/x-raw,format=NV12,width=640,height=480 ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=640,height=480 ! queue ! interpipesink name=camera1_rgba_nvmm forward-events=true forward-eos=true sync=false caps=video/x-raw(memory:NVMM),format=RGBA,width=640,height=480,pixel-aspect-ratio=1/1,interlace-mode=progressive,framerate=30/1')
pipelines_base.append(camera1_rgba_nvmm)

# Create Deepstream pipeline with 4 cameras processing
deepstream = PipelineEntity(client, 'deepstream', 'interpipesrc listen-to=camera0_rgba_nvmm ! nvstreammux0.sink_0 interpipesrc listen-to=camera0_rgba_nvmm ! nvstreammux0.sink_1 interpipesrc listen-to=camera1_rgba_nvmm ! nvstreammux0.sink_2 interpipesrc listen-to=camera1_rgba_nvmm ! nvstreammux0.sink_3 nvstreammux name=nvstreammux0 batch-size=4 batched-push-timeout=40000 width=640 height=480 ! queue ! nvinfer batch-size=4 config-file-path=../deepstream-models/config_infer_primary_4_cameras.txt ! queue ! nvtracker ll-lib-file=../deepstream-models/libnvds_mot_klt.so enable-batch-process=true ! queue ! nvmultistreamtiler width=640 height=480 rows=2 columns=2 ! nvvideoconvert ! nvdsosd ! queue ! interpipesink name=deep forward-events=true forward-eos=true sync=false')
pipelines_base.append(deepstream)

# Create display pipeline
display = PipelineEntity(client, 'display', 'interpipesrc listen-to=deep ! nvegltransform bufapi-version=true ! nveglglessink qos=false async=false sync=false')
pipelines_base.append(display)

# Play base pipelines
for pipeline in pipelines_base:
    pipeline.play()

print("Waiting...")
time.sleep(20)

for pipeline in pipelines_base:
    pipeline.stop()

# Delete pipelines
for pipeline in pipelines_base:
    pipeline.delete()

```

I'm seeing `Waiting...` and in the GSTD window as last `Using windsys: x11`... Then nothing...

**Comment by neilyoung** [comment]
I found the problem. My camera(s) are not well with YUY2. I switched to MJPG capture and it works.

Was expecting more feedback, though.

**Comment by arvindchandel** [comment]
Hi @neilyoung 
I am modifying the above app for 2 source, one rtsp camera and other mp4 file source. I kept the file same as you posted above except the rtsp source for camera 0 like below
# Create camera pipelines
camera0 = PipelineEntity(client, 'camera0', 'rtspsrc location=rtsp://ram:Yahoo600125@182.73.169.206:3554/Streaming/Channels/101 ! video/x-raw,format=YUY2,width=1280,height=720 ! interpipesink name=camera0 forward-events=true forward-eos=true sync=false')

and for camera 1, file source:
camera1 = PipelineEntity(client, 'camera1', 'filesrc location=/opt/nvidia/deepstream/deepstream-5.0/samples/streams/sample_cam5.mp4 ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue ! interpipesink name=camera1 forward-events=true forward-eos=true sync=false')

remaining pipeline is same as above but i am not able to run it, its ending with error below:

0:00:00.016106004  4155 0x556b1eb138c0 ERROR                gstdtcp gstd_tcp.c:136:gstd_tcp_create_socket_service:<GstdTcp@0x556b1e8dd010> Error binding to address: Address already in use
Error binding to address: Address already in use
Couldn't start IPC : (GstdTcp)
0:00:00.016157530  4155 0x556b1eb138c0 ERROR                   gstd gstd.c:310:main: Unable to start Gstd. Check (null) for more details.
Creating pipeline: camera0
0:02:36.381997563  4060 0x564bd72ec5e0 ERROR           gstdpipeline gstd_pipeline.c:511:gstd_pipeline_create:<GstdPipeline@0x7fec9810e8f0> Unable to create pipeline: no element "interpipesink"
0:02:36.382020616  4060 0x564bd72ec5e0 ERROR               gstdlist gstd_list.c:235:gstd_list_create:<GstdList@0x564bd7236d80> Could not create the resource  "camera0" on "pipelines"
Traceback (most recent call last):
  File "./media-server-new.py", line 43, in <module>
    camera0 = PipelineEntity(client, 'camera0', 'rtspsrc location=rtsp://ram:Yahoo600125@182.73.169.206:3554/Streaming/Channels/101 ! video/x-raw,format=YUY2,width=1280,height=720 ! interpipesink name=camera0 forward-events=true forward-eos=true sync=false')
  File "./media-server-new.py", line 13, in __init__
    self._client.pipeline_create(self._name, self._description)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 830, in pipeline_create
    self._send_cmd_line(['pipeline_create'] + parameters)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 232, in _send_cmd_line
    result['code'])
pygstc.gstcerror.GstdError: ('Bad pipeline description', 2)
[2]+  Exit 1                  DISPLAY=:0 gstd -

**Comment by neilyoung** [comment]
Sorry, this is something from a dark past. I have abandoned this approach a long time ago. Going with DeepStream SDK now on a Jetson Nano. Works great.
